# -*- coding: utf-8 -*-
"""Python_Verification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t7MsSE_lxK7Zb3WYo5ckeHpHOG2gJnf2
"""

import pandas as pd

# ------------------------------
# 1. CREATE THE DATASET
# ------------------------------
df = pd.DataFrame({
    "player": ["Player A", "Player B", "Player C", "Player D", "Player E"],
    "points": [463, 378, 311, 308, 203],
    "fg_pct": [40.7, 59.6, 52.8, 40.7, 40.3],
    "tp_pct": [26.8, 40.0, 43.2, 35.3, 32.1],
    "reb": [98, 317, 163, 66, 74],
    "ast": [73, 70, 45, 15, 134],
    "tov": [61, 72, 43, 35, 60],
})

print("DATASET:")
display(df)


# ------------------------------
# 2. HELPER TO SHOW SORTED STATS
# ------------------------------
def show_sorted(metric, ascending=False):
    print(f"\nSorted by {metric} ({'asc' if ascending else 'desc'}):")
    display(df.sort_values(by=metric, ascending=ascending)[["player", metric]])


# Show all supporting tables (good for your report)
show_sorted("points")
show_sorted("fg_pct")
show_sorted("tp_pct")
show_sorted("reb")
show_sorted("ast")
show_sorted("tov")


# ------------------------------
# 3. GROUND TRUTH ANSWERS
# ------------------------------
GT = {}

# H3_A – Turnovers matter most → highest turnovers
row = df.loc[df["tov"].idxmax()]
GT["H3_A"] = ("Highest turnovers", row["player"], row["tov"])

# H3_B – Rebounding matters most → highest rebounds
row = df.loc[df["reb"].idxmax()]
GT["H3_B"] = ("Highest rebounds", row["player"], row["reb"])

# H4_A – Efficiency priority → highest FG%
row = df.loc[df["fg_pct"].idxmax()]
GT["H4_A"] = ("Highest FG%", row["player"], row["fg_pct"])

# H4_B – Volume priority → highest points
row = df.loc[df["points"].idxmax()]
GT["H4_B"] = ("Highest points", row["player"], row["points"])

print("\nGROUND TRUTH FOR METRIC-BASED PROMPTS:")
for h, info in GT.items():
    rule, player, value = info
    print(f"{h}: {rule} -> {player} ({value})")


# ------------------------------
# 4. CLAIM CHECKING FUNCTION
# ------------------------------
def check_claim(prompt_id, claimed_player):
    """
    Example usage:
    check_claim("H3_A", "Player B")
    check_claim("H4_B", "Player A")
    """
    if prompt_id not in GT:
        print(f"{prompt_id}: No strict ground truth rule.")
        return

    rule, correct_player, value = GT[prompt_id]

    print(f"\nChecking claim for {prompt_id}")
    print(f"Rule: {rule}")
    print(f"Ground truth best: {correct_player}")
    print(f"Claimed: {claimed_player}")
    print("Aligned:", claimed_player == correct_player)


# ------------------------------
# 5. EXAMPLE CHECKS
# ------------------------------
print("\nEXAMPLE VERIFICATION:")
check_claim("H3_A", "Player B")  # replace with your actual JSON answers
check_claim("H3_B", "Player B")
check_claim("H4_A", "Player C")
check_claim("H4_B", "Player A")